theme = "native"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

