[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used/$total "

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(u:B) "
format_alt = " $icon_swap $swap_used.eng(u:B) "

[[block]]
block = "music"
format = " $icon { $combo.str(max_w:30,rot_interval:0.5)  $play $next |}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %R') "

